name: Update repo

#on:
#  schedule:
#    - cron:  '0,30 0-23 * * *'

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/Maxython/termux-packages-pacman
    - name: Update repo
      run: |
        cd termux-packages-pacman
        # Set profile git
        git config --global user.name "Maxython"
        git config --global user.email "mixython@gmail.com"
        git remote set-url origin "https://Maxython:${{ secrets.GITHUB_TOKEN }}@github.com/Maxython/termux-packages-pacman.git"
        # Create func
        list_pkg() {
          local list
          for i in $(git status -s packages | awk '{print $2}'); do
            local dir_sp=(${i//// })
            if [[ ! $(echo "$list" | grep "/${dir_sp[1]} ") ]]; then
              list+="packages/${dir_sp[1]} "
            fi
          done
          echo $list
        }
        info() {
          echo "==> $1"
        }
        commet() {
          echo "-> $1"
        }
        # Set git repo
        info "Set git repo"
        git remote add upstream https://github.com/termux/termux-packages.git
        git config pull.rebase false
        git fetch --all
        git pull upstream master || true
        git reset
        for i in $(grep -s -l ">>>>>>>" $(find . \( -path ./.git -o -path ./.github \) -prune -o -type f -not -name update-repo.sh)); do
          rm $i
          wget -O $i https://raw.githubusercontent.com/termux/termux-packages/master/$i
        done
        # Update system repo
        info "Update system repo"
        git add .
        git reset .github packages
        {
          git commit -m "Update repo"
          git push origin master
        } || true
        # Update repo packages
        info "Update repo packages"
        for i in $(list_pkg); do
          commet "${i}"
          git add $i
          git commit -m "${i}"
          git push origin master
        done
